In [2]:
import pandas as pd

MovieLens

In [3]:
movie_lens = "data/ml-latest-small"
links = pd.read_csv(f"{movie_lens}/links.csv")
movies = pd.read_csv(f"{movie_lens}/movies.csv")
ratings = pd.read_csv(f"{movie_lens}/ratings.csv")
tags = pd.read_csv(f"{movie_lens}/tags.csv")

In [4]:
print(f"movies: {movies.shape}")
print(f"ratings: {ratings.shape}")
print(f"tags: {tags.shape}")
print(f"links: {links.shape}")

movies: (86537, 3)
ratings: (33832162, 4)
tags: (2328315, 4)
links: (86537, 3)

Movies

In [5]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
movies["year"] = movies["title"].str.extract(r"\((\d{4})\)")

In [7]:
movies["year"] = movies["year"].astype("Int64")

In [8]:

movies["title"] = movies["title"].str.replace(r"\s*\(\d{4}\)$", "", regex=True).str.strip()

In [9]:
# movies['year_missing'] = movies['year'].isna().astype(int)

In [10]:
print(movies.isnull().sum())

movieId      0
title        0
genres       0
year       618
dtype: int64

In [11]:
movies.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

Ratings

In [12]:
print(ratings.isnull().sum())

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [13]:
ratings["timestamp"] = pd.to_datetime(ratings["timestamp"], unit="s")
ratings["year"], ratings["month"]  = ratings["timestamp"].dt.year, ratings["timestamp"].dt.month

In [14]:
ratings.duplicated().sum()

np.int64(0)

In [15]:
ratings.head()

   userId  movieId  rating           timestamp  year  month
0       1        1     4.0 2008-11-03 17:52:19  2008     11
1       1      110     4.0 2008-11-05 06:04:46  2008     11
2       1      158     4.0 2008-11-03 17:31:43  2008     11
3       1      260     4.5 2008-11-03 18:00:04  2008     11
4       1      356     5.0 2008-11-03 17:58:39  2008     11

Links

In [16]:
print(links.isnull().sum())

movieId      0
imdbId       0
tmdbId     126
dtype: int64

In [17]:
links["tmdbId"] = links["tmdbId"].astype("Int64")

In [18]:
links["imdbId"] = links["imdbId"].astype("Int64")

In [19]:
links.head()

   movieId  imdbId  tmdbId
0        1  114709     862
1        2  113497    8844
2        3  113228   15602
3        4  114885   31357
4        5  113041   11862

In [20]:
links.duplicated().sum()

np.int64(0)

Tags

In [21]:
print(tags.isnull().sum())

userId        0
movieId       0
tag          17
timestamp     0
dtype: int64

In [22]:
tags["timestamp"] = pd.to_datetime(tags["timestamp"], unit="s")
tags["year"], tags["month"]  = tags["timestamp"].dt.year, tags["timestamp"].dt.month

In [23]:
tags.head()

   userId  movieId            tag           timestamp  year  month
0      10      260   good vs evil 2015-05-03 15:22:38  2015      5
1      10      260  Harrison Ford 2015-05-03 15:21:45  2015      5
2      10      260         sci-fi 2015-05-03 15:22:18  2015      5
3      14     1221      Al Pacino 2011-07-25 13:32:36  2011      7
4      14     1221          mafia 2011-07-25 13:32:26  2011      7

In [24]:
movies.to_csv("data/ml-latest-small/movies_cleaned.csv", index=False)
ratings.to_csv("data/ml-latest-small/ratings_cleaned.csv", index=False)
links.to_csv("data/ml-latest-small/links_cleaned.csv", index=False)
tags.to_csv("data/ml-latest-small/tags_cleaned.csv", index=False)

The Movies Dataset

In [25]:
movies_dataset = "data/archive"
credits_md = pd.read_csv(f"{movies_dataset}/credits.csv")
keywords_md = pd.read_csv(f"{movies_dataset}/keywords.csv")
links_md = pd.read_csv(f"{movies_dataset}/links.csv")
links_small_md = pd.read_csv(f"{movies_dataset}/links_small.csv")
movies_metadata_md = pd.read_csv(f"{movies_dataset}/movies_metadata.csv", low_memory=False)
ratings_md = pd.read_csv(f"{movies_dataset}/ratings.csv")
ratings_small_md = pd.read_csv(f"{movies_dataset}/ratings_small.csv")

In [26]:
print(f"credits: {credits_md.shape}")
print(f"keywords: {keywords_md.shape}")
print(f"links: {links_md.shape}")
print(f"links_small: {links_small_md.shape}")
print(f"movies_metadata: {movies_metadata_md.shape}")
print(f"ratings: {ratings_md.shape}")
print(f"ratings_small: {ratings_small_md.shape}")

credits: (45476, 3)
keywords: (46419, 2)
links: (45843, 3)
links_small: (9125, 3)
movies_metadata: (45466, 24)
ratings: (26024289, 4)
ratings_small: (100004, 4)

Credits

In [27]:
credits_md.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [28]:
import ast

credits_md['cast'] = credits_md['cast'].apply(ast.literal_eval)
credits_md['crew'] = credits_md['crew'].apply(ast.literal_eval)

def get_cast(cast_list, n=5):
    return [actor['name'] for actor in cast_list[:n]]

def get_director(crew_list):
    for person in crew_list:
        if person['job'] == 'Director':
            return person['name']
    return None

def get_writers(crew_list):
    writers = []
    for person in crew_list:
        if person['department'] == 'Writing':
            writers.append(person['name'])
    return writers[:3]

credits_md['cast_main'] = credits_md['cast'].apply(get_cast)
credits_md['director'] = credits_md['crew'].apply(get_director)
credits_md['writers'] = credits_md['crew'].apply(get_writers)

credits_md['cast_main'] = credits_md['cast_main'].apply(lambda x: " ".join(x))
credits_md['writers'] = credits_md['writers'].apply(lambda x: " ".join(x))

credits_md = credits_md[['id', 'cast_main', 'director', 'writers']]

In [29]:
print(credits_md.isnull().sum())

id             0
cast_main      0
director     887
writers        0
dtype: int64

In [30]:
credits_md["director"] = credits_md["director"].fillna("unknown")

In [32]:
credits_md.duplicated().sum()

np.int64(40)

In [33]:
credits_md = credits_md.drop_duplicates()
credits_md.duplicated().sum()

np.int64(0)

Keywords

In [34]:
keywords_md.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [35]:
import ast

keywords_md["keywords"] = keywords_md["keywords"].apply(ast.literal_eval)

def get_keywords(keyword_list):
    words = []
    for item in keyword_list:
        word = item["name"].lower().replace(" ", "_")
        words.append(word)
    return words

keywords_md["keywords_clean"] = keywords_md["keywords"].apply(get_keywords)
keywords_md["keywords_clean"] = keywords_md["keywords_clean"].apply(lambda x: " ".join(x))

keywords_md = keywords_md[["id", "keywords_clean"]]

In [36]:
print(keywords_md.isnull().sum())

id                0
keywords_clean    0
dtype: int64

In [37]:
credits_md.duplicated().sum()

np.int64(0)

Links

In [38]:
links_md.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [39]:
links_md["imdbId"] = links_md["imdbId"].astype("Int64")
links_small_md["imdbId"] = links_small_md["imdbId"].astype("Int64")
links_md["tmdbId"] = links_md["tmdbId"].astype("Int64")
links_small_md["tmdbId"] = links_small_md["tmdbId"].astype("Int64")

In [40]:
links.duplicated().sum()

np.int64(0)

Movies metadata

In [41]:
movies_metadata_md.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [44]:
movies_metadata_md = movies_metadata_md[movies_metadata_md['id'].str.isnumeric()]
movies_metadata_md['id'] = movies_metadata_md['id'].astype("Int64")

In [45]:
import ast

def parse_json(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

def get_names(list_obj):
    names = []
    for item in list_obj:
        if isinstance(item, dict) and "name" in item:
            names.append(item["name"].lower().replace(" ", "_"))
    return " ".join(names)

def get_collection(x):
    try:
        obj = ast.literal_eval(x)
        return obj["name"].lower().replace(" ", "_")
    except:
        return ""

movies_metadata_md["genres"] = (
    movies_metadata_md["genres"]
    .apply(parse_json)
    .apply(get_names)
)

movies_metadata_md["production_companies"] = (
    movies_metadata_md["production_companies"]
    .apply(parse_json)
    .apply(get_names)
)

movies_metadata_md["production_countries"] = (
    movies_metadata_md["production_countries"]
    .apply(parse_json)
    .apply(get_names)
)

movies_metadata_md["spoken_languages"] = (
    movies_metadata_md["spoken_languages"]
    .apply(parse_json)
    .apply(get_names)
)

movies_metadata_md["belongs_to_collection"] = (
    movies_metadata_md["belongs_to_collection"]
    .apply(get_collection)
)

In [49]:
movies_metadata_md = movies_metadata_md.drop_duplicates()
movies_metadata_md.duplicated().sum()

np.int64(0)

In [50]:
print(movies_metadata_md.isnull().sum())

adult                        0
belongs_to_collection        0
budget                       0
genres                       0
homepage                 37669
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   3
poster_path                386
production_companies         0
production_countries         0
release_date                87
revenue                      3
runtime                    260
spoken_languages             0
status                      84
tagline                  25039
title                        3
video                        3
vote_average                 3
vote_count                   3
dtype: int64

In [51]:
text_cols = ["homepage", "overview", "tagline", "status", "original_language", "poster_path"]
movies_metadata_md[text_cols] = movies_metadata_md[text_cols].fillna("unknown")

In [52]:
int_cols = ["budget", "revenue", "runtime", "vote_count"]

for col in int_cols:
    movies_metadata_md[col] = movies_metadata_md[col].astype("Int64")

float_cols = ["vote_average", "popularity"]
for col in float_cols:
    movies_metadata_md[col] = movies_metadata_md[col].astype("float64")

Ratings

In [53]:
ratings_md.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [57]:
ratings_md.duplicated().sum()

np.int64(0)

In [58]:
ratings_small_md.duplicated().sum()

np.int64(0)

In [59]:
print(ratings_md.isnull().sum())
print(ratings_small_md.isnull().sum())

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [60]:
credits_md.to_csv("data/archive/credits_cleaned.csv", index=False)
links_md.to_csv("data/archive/links_cleaned.csv", index=False)
links_small_md.to_csv("data/archive/links_small_cleaned.csv", index=False)
movies_metadata_md.to_csv("data/archive/movies_metadata_cleaned.csv", index=False)
keywords_md.to_csv("data/archive/keywords_cleaned.csv", index=False)
ratings_md.to_csv("data/archive/ratings_cleaned.csv", index=False)
ratings_small_md.to_csv("data/archive/ratings_small_cleaned.csv", index=False)

The Movies Dataset i MovieLens łączymy za pomocą links.csv