In [163]:
import pandas as pd

MovieLens

In [164]:
movie_lens = "data/ml-latest-small"
links = pd.read_csv(f"{movie_lens}/links.csv")
movies = pd.read_csv(f"{movie_lens}/movies.csv")
ratings = pd.read_csv(f"{movie_lens}/ratings.csv")
tags = pd.read_csv(f"{movie_lens}/tags.csv")

In [165]:
print(f"movies: {movies.shape}")
print(f"ratings: {ratings.shape}")
print(f"tags: {tags.shape}")
print(f"links: {links.shape}")

movies: (9742, 3)
ratings: (100836, 4)
tags: (3683, 4)
links: (9742, 3)

Movies

In [166]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [167]:
movies["year"] = movies["title"].str.extract(r"\((\d{4})\)")

In [168]:
movies["year"] = movies["year"].astype("Int64")

In [169]:

movies["title"] = movies["title"].str.replace(r"\s*\(\d{4}\)$", "", regex=True).str.strip()

In [170]:
# movies['year_missing'] = movies['year'].isna().astype(int)

In [171]:
print(movies.isnull().sum())

movieId     0
title       0
genres      0
year       13
dtype: int64

In [172]:
movies.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

Ratings

In [173]:
print(ratings.isnull().sum())

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [174]:
ratings["timestamp"] = pd.to_datetime(ratings["timestamp"], unit="s")
ratings["year"], ratings["month"]  = ratings["timestamp"].dt.year, ratings["timestamp"].dt.month

In [175]:
ratings.duplicated().sum()

np.int64(0)

In [176]:
ratings.head()

   userId  movieId  rating           timestamp  year  month
0       1        1     4.0 2000-07-30 18:45:03  2000      7
1       1        3     4.0 2000-07-30 18:20:47  2000      7
2       1        6     4.0 2000-07-30 18:37:04  2000      7
3       1       47     5.0 2000-07-30 19:03:35  2000      7
4       1       50     5.0 2000-07-30 18:48:51  2000      7

Links

In [177]:
print(links.isnull().sum())

movieId    0
imdbId     0
tmdbId     8
dtype: int64

In [178]:
links["tmdbId"] = links["tmdbId"].astype("Int64")

In [179]:
links["imdbId"] = links["imdbId"].astype("Int64")

In [180]:
links.head()

   movieId  imdbId  tmdbId
0        1  114709     862
1        2  113497    8844
2        3  113228   15602
3        4  114885   31357
4        5  113041   11862

In [181]:
links.duplicated().sum()

np.int64(0)

Tags

In [182]:
print(tags.isnull().sum())

userId       0
movieId      0
tag          0
timestamp    0
dtype: int64

In [183]:
tags["timestamp"] = pd.to_datetime(tags["timestamp"], unit="s")
tags["year"], tags["month"]  = tags["timestamp"].dt.year, tags["timestamp"].dt.month

In [184]:
tags.head()

   userId  movieId              tag           timestamp  year  month
0       2    60756            funny 2015-10-24 19:29:54  2015     10
1       2    60756  Highly quotable 2015-10-24 19:29:56  2015     10
2       2    60756     will ferrell 2015-10-24 19:29:52  2015     10
3       2    89774     Boxing story 2015-10-24 19:33:27  2015     10
4       2    89774              MMA 2015-10-24 19:33:20  2015     10

In [151]:
movies.to_csv("data/ml-latest-small/movies_cleaned.csv", index=False)
ratings.to_csv("data/ml-latest-small/ratings_cleaned.csv", index=False)
links.to_csv("data/ml-latest-small/links_cleaned.csv", index=False)
tags.to_csv("data/ml-latest-small/tags_cleaned.csv", index=False)

The Movies Dataset

The Movies Dataset i MovieLens za pomocą links.csv

In [185]:
movies_dataset = "data/archive"
credits_md = pd.read_csv(f"{movies_dataset}/credits.csv")
keywords_md = pd.read_csv(f"{movies_dataset}/keywords.csv")
links_md = pd.read_csv(f"{movies_dataset}/links.csv")
links_small_md = pd.read_csv(f"{movies_dataset}/links_small.csv")
movies_metadata_md = pd.read_csv(f"{movies_dataset}/movies_metadata.csv", low_memory=False)
ratings_md = pd.read_csv(f"{movies_dataset}/ratings.csv")
ratings_small_md = pd.read_csv(f"{movies_dataset}/ratings_small.csv")

In [186]:
print(f"credits: {credits_md.shape}")
print(f"keywords: {keywords_md.shape}")
print(f"links: {links_md.shape}")
print(f"links_small: {links_small_md.shape}")
print(f"movies_metadata: {movies_metadata_md.shape}")
print(f"ratings: {ratings_md.shape}")
print(f"ratings_small: {ratings_small_md.shape}")

credits: (45476, 3)
keywords: (46419, 2)
links: (45843, 3)
links_small: (9125, 3)
movies_metadata: (45466, 24)
ratings: (26024289, 4)
ratings_small: (100004, 4)

In [187]:
links_md["imdbId"] = links_md["imdbId"].astype("Int64")
links_small_md["imdbId"] = links_small_md["imdbId"].astype("Int64")